# ~/.config/starship.toml
add_newline = false

[character] 
success_symbol = "[π](bold green)"
vicmd_symbol = "[π](bold cyan)"
vimcmd_replace_one_symbol = "[π](bold orange)"
vimcmd_replace_symbol = "[π](bold orange)"
vimcmd_visual_symbol = "[π](bold purple)"

[line_break]
disabled = true

[cmd_duration]
min_time = 10_000  
format = " took [$duration]($style)"
