[redshift]
temp-day=6500
temp-night=3500
fade=1
dawn-time=6:00-6:10
dusk-time=18:35-20:15
brightness-day=0.85
brightness-night=0.65
gamma=0.8
location-provider=manual
adjustment-method=randr
[manual]
lat=-31.4135
lon=-64.18105
[randr]
